apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-n4bg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-n4bg@sha256:dd18ce08e8a6e532165e2506404691bc6dad59ecf5b2217134037a0c838b70c7
        name: my-nodejs
        resources: {}
status: {}
